//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh không được để trống.
        /// </summary>
        internal static string AnhCannotBeBlank {
            get {
                return ResourceManager.GetString("AnhCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo sản phẩm thất bại.
        /// </summary>
        internal static string CreateSPFail {
            get {
                return ResourceManager.GetString("CreateSPFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm người dùng thất bại.
        /// </summary>
        internal static string CreateUserFail {
            get {
                return ResourceManager.GetString("CreateUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        internal static string EmailCannotBeBlank {
            get {
                return ResourceManager.GetString("EmailCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hợp lệ.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người người dùng không được trống.
        /// </summary>
        internal static string FullnameCannotBeBlank {
            get {
                return ResourceManager.GetString("FullnameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá sản phẩm không đươc để trống.
        /// </summary>
        internal static string GiaCannotBeBlank {
            get {
                return ResourceManager.GetString("GiaCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả sp không được để trống.
        /// </summary>
        internal static string MoTaSPCannotBeBlank {
            get {
                return ResourceManager.GetString("MoTaSPCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được để trống.
        /// </summary>
        internal static string PhoneCannotBeBlank {
            get {
                return ResourceManager.GetString("PhoneCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm đã tồn tại.
        /// </summary>
        internal static string SanPhamAlreadyExists {
            get {
                return ResourceManager.GetString("SanPhamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm không được để trống.
        /// </summary>
        internal static string TenspCannotBeBlank {
            get {
                return ResourceManager.GetString("TenspCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa không thành công.
        /// </summary>
        internal static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản không được để trổng.
        /// </summary>
        internal static string UsernameCannotBeBlank {
            get {
                return ResourceManager.GetString("UsernameCannotBeBlank", resourceCulture);
            }
        }
    }
}
